### ISSUE TITLE
I get an error says "grpcCallMethod Exception"

### ISSUE THREAD

**Issue by joan2015** [zalopay-oss/jmeter-grpc-plugin#1]
I follow the readme and get an error like this 
2020-03-20 21:57:45,712 INFO o.j.g.c.GrpcClientSampler: grpcCallMethod
2020-03-20 21:57:45,712 ERROR o.j.g.c.GrpcClientSampler: grpcCallMethod Exception
java.lang.NoSuchMethodException: greet.GreeterGrpc$GreeterBlockingStub.SayHello(greet.HelloRequest)
how can I fix this?

**Comment by thoainguyen** [comment]
Can you give me your *.proto and *.jmx files?
For the error is displayed,  I can guess some problem can happen:
* The method must begin by lowercase: example sayHello but not SayHello
* Is your full packagename is only `greet`.

**Comment by datuanmac** [comment]
I follow command:
apache-jmeter-5.2/bin/jmeter.sh -n -H rep.proxy.nic.fujitsu.com -P 8080 -u fvlduy -a 3008199101 -t GrpcClientSampler.jmx -l result.csv
Picked up _JAVA_OPTIONS: -Xmx4096m
Error in NonGUIDriver java.lang.NullPointerException
An error occurred: Error in NonGUIDriver null
How can I fix this error ?

**Comment by A1Darkwing** [comment]
hi @datuanmac, please attach ur proto? And check @thoainguyen' comment.

**Comment by datuanmac** [comment]
> hi @datuanmac, please attach ur proto? And check @thoainguyen' comment.

I try used command : apache-jmeter-5.2/bin/jmeter.sh -n -t hello.jmx -l result.csv
But got  same error:
Picked up _JAVA_OPTIONS: -Xmx4096m
Error in NonGUIDriver java.lang.NullPointerException
An error occurred: Error in NonGUIDriver null

**Comment by thoainguyen** [comment]
Hello @datuanmac, before you run that command, please ensure :
1) The dependency `jmeter-grpc-client-sampler.jar` is coppied into `apache-jmeter-5.2/lib/ext`
2) The `*.jar` file after build `*.proto` file is also in `apache-jmeter-5.2/lib/ext`

**Comment by thoainguyen** [comment]
Close this issue due to inactivity.
