### ISSUE TITLE
Disable SSL verifications in netty by default

### ISSUE THREAD

**Issue by danielochoaglobant** [zalopay-oss/jmeter-grpc-plugin#11]
Load testing with ssl enabled is usual in test environments that use self signed and not well crafted certs. 
The idea is to bypass checking the validity of the certs by default.

**Comment by thoainguyen** [comment]
@danielochoaglobant if we load test a system which has been load balancing over domain (use nginx, v,.v,.) by scale multiple instance on same url, you can need enable ssl for that purpose.
