### ISSUE TITLE
NoSuchMethodError on com.google.common.base

### ISSUE THREAD

**Issue by aleksandar-spasojevic** [zalopay-oss/jmeter-grpc-plugin#3]
Dear All,

I've tried to use this plugin, but failed to do so. 
A basic example on Mac OS X (10.15.4):

- download repo
- execute ```mvn clean install``` in root folder with java **1.8.232** (Zulu)
- move ```jmeter-grpc-client-sampler.jar``` to _{jmeter_home}/lib/ext_
- go to _docs/example/grpc-lib_
- put my ```measurements.proto``` into _src/main/proto_

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "ch.zhaw.grpc";
option java_outer_classname = "Measurements";
option objc_class_prefix = "HLW";

package ch.zhaw.grpc;

import "google/protobuf/timestamp.proto";

service MeasurementsService {
  rpc send (MeasurementsRequest) returns (MeasurementsReply) {}
}

message MeasurementsRequest {
  google.protobuf.Timestamp timeValue = 1;
  int32 value = 2;
}

message MeasurementsReply {
  string timeValue = 1;
  int32 value = 2;
}
```

- execute ```mvn clean install``` with java **1.8.232** (Zulu)
- move ```grpc-lib-0.0.1.jar``` to _{jmeter_home}/lib/ext_

Now make a Test Plan in order to try a GRPC Sampler, which fails due to missing Method. The funny thing is, if I execute in the very same session once again, I get an other error, namely  

**First try**
![image](https://user-images.githubusercontent.com/1368389/78512791-adf54e80-77a7-11ea-8fcb-905cc31055f4.png)
 
**Second try (in the same session, just seconds after**
![image](https://user-images.githubusercontent.com/1368389/78512848-117f7c00-77a8-11ea-9b30-94aaf279df10.png)

Best regards
Aleks

**Comment by thoainguyen** [comment]
Hi, Thanks for your detailed description, your issue may be due to incompatible dependencies
Try to recompile jmeter-grpc-client-sampler.jar: 

+ Change version com.google.guava in pom.xml to the newer:
```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.2-jre</version>
        </dependency>
```
+ In requestBuilderCode, add `import java.time.Instant;`

**Comment by aleksandar-spasojevic** [comment]
Hi there,
thanks for your prompt response 👍.
I tried so, but without any success:

![image](https://user-images.githubusercontent.com/1368389/78530719-7953b800-77e4-11ea-9295-dc5b6473463a.png)

I still get the very same error message

![image](https://user-images.githubusercontent.com/1368389/78530769-8f617880-77e4-11ea-9ed8-844f2cedb4be.png)

**Comment by thoainguyen** [comment]
Hi @aleksandar-spasojevic, sorry for the late response,
Your JMeter which you installed via `brew install jmeter` maybe contains another dependency that causes this problem, Do you try to install the new one or portable one in [here](https://jmeter.apache.org/download_jmeter.cgi)
Best regards

**Comment by aleksandar-spasojevic** [comment]
Hi @thoainguyen 
thanks for your response. Since I have the urge to load test (bachelor thesis) my application, I was forced to do my tests in https://locust.io . Due to the current situation, I am not able to investigate further. I hope you understand.
Best regards
Aleks
