### ISSUE TITLE
> hi @datuanmac, please attach ur proto? And check @thoainguyen' comment.

### ISSUE THREAD

**Issue by datuanmac** [zalopay-oss/jmeter-grpc-plugin#4]
> hi @datuanmac, please attach ur proto? And check @thoainguyen' comment.

I try used command : apache-jmeter-5.2/bin/jmeter.sh -n -t hello.jmx -l result.csv
But got  same error:
Picked up _JAVA_OPTIONS: -Xmx4096m
Error in NonGUIDriver java.lang.NullPointerException
An error occurred: Error in NonGUIDriver null

_Originally posted by @datuanmac in https://github.com/zalopay-oss/jmeter-grpc-plugin/issues/1#issuecomment-604908876_

I ran completed without ".sh". Please check It and update document

**Comment by thoainguyen** [comment]
Thank you !
